name: New release

on:
    push:
        branches:
            - main

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        outputs:
            releases_created: ${{ steps.release.outputs.releases_created }}
        steps:
            - name: Release
              id: release
              uses: google-github-actions/release-please-action@v3
              with:
                  command: manifest

            - name: test
              run: |
                  echo ${{ steps.release.outputs.releases_created }}

    publish:
        needs: release
        name: Publish
        runs-on: ubuntu-latest
        if: ${{ needs.release.outputs.releases_created }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "yarn"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Build
              working-directory: idkit
              run: yarn build

            - name: Publish
              run: npm publish
              working-directory: idkit
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
